import {
  SchoolProfile,
  SchoolYear,
  GradeLevel,
  TrackProgram,
  StrandSpecialization,
  Room,
  Section,
  Subject,
  Teacher,
  TeacherAssignment,
  Schedule,
  Student,
  StudentEnrollment,
  GradeRecord,
  Announcement,
  AuditLog,
  User,
  RolePermissionConfig,
} from '../types';

export const initialSchoolProfile: SchoolProfile = {
  id: 'sha-main-profile',
  name: 'SACRED HEART ACADEMY',
  schoolId: '403696',
  tagline: 'Excellence in Faith, Character, and Wisdom',
  location: 'Barangay 3, Garchitorena, Camarines Sur, Philippines',
  address: 'Barangay 3, Garchitorena, 4428 Camarines Sur, Philippines',
  division: 'Division of Camarines Sur',
  region: 'Region V (Bicol Region)',
  contactNumber: '+63 917 555 4321 / (054) 881-2345',
  email: 'admin@sacredheartacademy-garchitorena.edu.ph',
  headOfficial: 'Atty. Rammonete Shirlyn G. Piano',
  headTitle: 'School Head',
  schoolHead: 'Atty. Rammonete Shirlyn G. Piano',
  principalOfficial: 'Ellen Baider',
  principalTitle: 'School Principal',
  principal: 'Ellen Baider',
  registrarOfficial: 'Ruben Martirez',
  registrarTitle: 'School Registrar',
  registrar: 'Ruben Martirez',
  currentSchoolYearId: 'sy-2026-2027',
  currentGradingPeriod: 'Q1',
  gradingScalePassing: 75,
};

export const initialSchoolYears: SchoolYear[] = [
  {
    id: 'sy-2026-2027',
    name: '2026–2027',
    startDate: '2026-08-01',
    endDate: '2027-05-30',
    isActive: true,
    isClosed: false,
    isArchived: false,
  },
  {
    id: 'sy-2025-2026',
    name: '2025–2026',
    startDate: '2025-08-01',
    endDate: '2026-05-30',
    isActive: false,
    isClosed: true,
    isArchived: false,
  },
];

export const initialGradeLevels: GradeLevel[] = [
  { id: 'gl-7', name: 'Grade 7', levelNumber: 7, category: 'JHS' },
  { id: 'gl-8', name: 'Grade 8', levelNumber: 8, category: 'JHS' },
  { id: 'gl-9', name: 'Grade 9', levelNumber: 9, category: 'JHS' },
  { id: 'gl-10', name: 'Grade 10', levelNumber: 10, category: 'JHS' },
  { id: 'gl-11', name: 'Grade 11', levelNumber: 11, category: 'SHS' },
  { id: 'gl-12', name: 'Grade 12', levelNumber: 12, category: 'SHS' },
];

export const initialTracks: TrackProgram[] = [
  {
    id: 'track-acad',
    name: 'Academic Strand',
    code: 'ACAD',
    description: 'Senior High School Academic Programs preparing students for higher education.',
  },
  {
    id: 'track-techpro',
    name: 'TechPro',
    code: 'TECHPRO',
    description: 'Technical-Vocational-Livelihood Programs empowering students with professional certifications and practical skills.',
  },
];

export const initialStrands: StrandSpecialization[] = [
  {
    id: 'strand-stem',
    trackProgramId: 'track-acad',
    name: 'STEM (Science, Technology, Engineering & Math)',
    code: 'STEM',
    description: 'Academic strand focusing on advanced sciences, mathematics, and technology.',
  },
  {
    id: 'strand-abm',
    trackProgramId: 'track-acad',
    name: 'ABM (Accountancy, Business & Management)',
    code: 'ABM',
    description: 'Academic strand focusing on entrepreneurship, financial management, and business administration.',
  },
  {
    id: 'strand-humss',
    trackProgramId: 'track-acad',
    name: 'HUMSS (Humanities & Social Sciences)',
    code: 'HUMSS',
    description: 'Academic strand for literature, social sciences, communication, and education.',
  },
  {
    id: 'strand-gas',
    trackProgramId: 'track-acad',
    name: 'GAS (General Academic Strand)',
    code: 'GAS',
    description: 'Flexible academic program covering cross-disciplinary studies.',
  },
  {
    id: 'strand-ict',
    trackProgramId: 'track-techpro',
    name: 'Information & Communications Technology (ICT)',
    code: 'TECHPRO-ICT',
    description: 'TechPro specialization in computer hardware servicing, programming, and web development.',
  },
  {
    id: 'strand-he',
    trackProgramId: 'track-techpro',
    name: 'Home Economics (HE) & Hospitality Services',
    code: 'TECHPRO-HE',
    description: 'TechPro specialization in cookery, bread and pastry, and food & beverage services.',
  },
  {
    id: 'strand-ia',
    trackProgramId: 'track-techpro',
    name: 'Industrial Arts & Technical Drafting',
    code: 'TECHPRO-IA',
    description: 'TechPro specialization in electrical installation, maintenance, and technical drafting.',
  },
];

export const initialRooms: Room[] = [
  { id: 'rm-1', name: 'Room 1', building: 'Main Academic Hall - 1st Floor', capacity: 45, status: 'Available' },
  { id: 'rm-2', name: 'Room 2', building: 'Main Academic Hall - 1st Floor', capacity: 45, status: 'Available' },
  { id: 'rm-3', name: 'Room 3', building: 'Main Academic Hall - 2nd Floor', capacity: 45, status: 'Available' },
  { id: 'rm-4', name: 'Room 4', building: 'Main Academic Hall - 2nd Floor', capacity: 45, status: 'Available' },
  { id: 'rm-5', name: 'Room 5', building: 'Senior High Pavilion - 1st Floor', capacity: 40, status: 'Available' },
  { id: 'rm-6', name: 'Room 6', building: 'Senior High Pavilion - 2nd Floor', capacity: 40, status: 'Available' },
  { id: 'rm-sci', name: 'Science Laboratory', building: 'Science & Discovery Center', capacity: 35, status: 'Available' },
  { id: 'rm-tle', name: 'TechPro & TLE Workshop', building: 'Technical Education Building', capacity: 35, status: 'Available' },
  { id: 'rm-com', name: 'Computer Laboratory', building: 'Main Academic Hall - 2nd Floor', capacity: 40, status: 'Available' },
  { id: 'rm-avr', name: 'Audio-Visual Room (AVR)', building: 'Administration Wing', capacity: 80, status: 'Available' },
];

export const initialTeachers: Teacher[] = [
  { id: 'tch-austin', teacherId: 'TCH-001', firstName: 'Austin', lastName: '', fullName: 'Austin', contactNumber: '0918-111-2233', email: 'austin@sacredheartacademy.edu.ph', username: 'austin', accountStatus: 'Active', specialization: 'Mathematics & ESP' },
  { id: 'tch-eunilyn', teacherId: 'TCH-002', firstName: 'Eunilyn', lastName: '', fullName: 'Eunilyn', contactNumber: '0918-222-3344', email: 'eunilyn@sacredheartacademy.edu.ph', username: 'eunilyn', accountStatus: 'Active', specialization: 'Science (Junior High)' },
  { id: 'tch-angela', teacherId: 'TCH-003', firstName: 'Angela', lastName: '', fullName: 'Angela', contactNumber: '0918-333-4455', email: 'angela@sacredheartacademy.edu.ph', username: 'angela', accountStatus: 'Active', specialization: 'Technology & Livelihood Education (TLE)' },
  { id: 'tch-jenneth', teacherId: 'TCH-004', firstName: 'Jenneth', lastName: '', fullName: 'Jenneth', contactNumber: '0918-444-5566', email: 'jenneth@sacredheartacademy.edu.ph', username: 'jenneth', accountStatus: 'Active', specialization: 'English Language & Literature' },
  { id: 'tch-merilyn', teacherId: 'TCH-005', firstName: 'Merilyn', lastName: '', fullName: 'Merilyn', contactNumber: '0918-555-6677', email: 'merilyn@sacredheartacademy.edu.ph', username: 'merilyn', accountStatus: 'Active', specialization: 'Mathematics & ESP' },
  { id: 'tch-jhopay', teacherId: 'TCH-006', firstName: 'Jhopay', lastName: '', fullName: 'Jhopay', contactNumber: '0918-666-7788', email: 'jhopay@sacredheartacademy.edu.ph', username: 'jhopay', accountStatus: 'Active', specialization: 'Filipino Wika at Panitikan' },
  { id: 'tch-judith', teacherId: 'TCH-007', firstName: 'Judith', lastName: '', fullName: 'Judith', contactNumber: '0918-777-8899', email: 'judith@sacredheartacademy.edu.ph', username: 'judith', accountStatus: 'Active', specialization: 'MAPEH (Music, Arts, PE, Health)' },
  { id: 'tch-lyncha', teacherId: 'TCH-008', firstName: 'Lyncha', lastName: '', fullName: 'Lyncha', contactNumber: '0918-888-9900', email: 'lyncha@sacredheartacademy.edu.ph', username: 'lyncha', accountStatus: 'Active', specialization: 'Araling Panlipunan (Social Studies)' },
  { id: 'tch-teresita', teacherId: 'TCH-009', firstName: 'Teresita', lastName: '', fullName: 'Teresita', contactNumber: '0918-999-0011', email: 'teresita@sacredheartacademy.edu.ph', username: 'teresita', accountStatus: 'Active', specialization: 'Edukasyon sa Pagpapakatao (ESP)' },
  { id: 'tch-kimberly', teacherId: 'TCH-010', firstName: 'Kimberly', lastName: '', fullName: 'Kimberly', contactNumber: '0919-111-2233', email: 'kimberly@sacredheartacademy.edu.ph', username: 'kimberly', accountStatus: 'Active', specialization: 'TLE & Filipino' },
  { id: 'tch-necyl', teacherId: 'TCH-011', firstName: 'Necyl', lastName: '', fullName: 'Necyl', contactNumber: '0919-222-3344', email: 'necyl@sacredheartacademy.edu.ph', username: 'necyl', accountStatus: 'Active', specialization: 'Science & TLE' },
  { id: 'tch-diosdado', teacherId: 'TCH-012', firstName: 'Diosdado', lastName: '', fullName: 'Diosdado', contactNumber: '0919-333-4455', email: 'diosdado@sacredheartacademy.edu.ph', username: 'diosdado', accountStatus: 'Active', specialization: 'MAPEH & Sports' },
  { id: 'tch-leonor', teacherId: 'TCH-013', firstName: 'Leonor', lastName: '', fullName: 'Leonor', contactNumber: '0919-444-5566', email: 'leonor@sacredheartacademy.edu.ph', username: 'leonor', accountStatus: 'Active', specialization: 'Araling Panlipunan & History' },
  { id: 'tch-mergie', teacherId: 'TCH-014', firstName: 'Mergie', lastName: '', fullName: 'Mergie', contactNumber: '0919-555-6677', email: 'mergie@sacredheartacademy.edu.ph', username: 'mergie', accountStatus: 'Active', specialization: 'Mathematics & ESP' },
  { id: 'tch-reven', teacherId: 'TCH-015', firstName: 'Reven', lastName: '', fullName: 'Reven', contactNumber: '0919-666-7788', email: 'reven@sacredheartacademy.edu.ph', username: 'reven', accountStatus: 'Active', specialization: 'English & Communication' },
  { id: 'tch-sheilamae', teacherId: 'TCH-016', firstName: 'Sheila Mae', lastName: '', fullName: 'Sheila Mae', contactNumber: '0919-777-8899', email: 'sheilamae@sacredheartacademy.edu.ph', username: 'sheilamae', accountStatus: 'Active', specialization: 'Science & Filipino' },
  { id: 'tch-morano', teacherId: 'TCH-017', firstName: 'Morano', lastName: '', fullName: 'Morano', contactNumber: '0919-888-9900', email: 'morano@sacredheartacademy.edu.ph', username: 'morano', accountStatus: 'Active', specialization: 'Science (Physical & Biological)' },
];

export const initialSections: Section[] = [
  { id: 'sec-7a', name: 'Grade 7 - St. Joseph', gradeLevelId: 'gl-7', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-austin', roomId: 'rm-1', status: 'Active' },
  { id: 'sec-7b', name: 'Grade 7 - St. Jude', gradeLevelId: 'gl-7', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-eunilyn', roomId: 'rm-2', status: 'Active' },
  { id: 'sec-8a', name: 'Grade 8 - St. Francis', gradeLevelId: 'gl-8', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-jenneth', roomId: 'rm-3', status: 'Active' },
  { id: 'sec-8b', name: 'Grade 8 - St. Clare', gradeLevelId: 'gl-8', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-angela', roomId: 'rm-4', status: 'Active' },
  { id: 'sec-9a', name: 'Grade 9 - St. Anthony', gradeLevelId: 'gl-9', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-merilyn', roomId: 'rm-1', status: 'Active' },
  { id: 'sec-10a', name: 'Grade 10 - St. Benedict', gradeLevelId: 'gl-10', schoolYearId: 'sy-2026-2027', adviserTeacherId: 'tch-jhopay', roomId: 'rm-2', status: 'Active' },
  { id: 'sec-11-acad', name: 'Grade 11 - Academic Strand (STEM/ABM)', gradeLevelId: 'gl-11', schoolYearId: 'sy-2026-2027', trackProgramId: 'track-acad', strandSpecializationId: 'strand-stem', adviserTeacherId: 'tch-morano', roomId: 'rm-5', status: 'Active' },
  { id: 'sec-11-tech', name: 'Grade 11 - TechPro (ICT & HE)', gradeLevelId: 'gl-11', schoolYearId: 'sy-2026-2027', trackProgramId: 'track-techpro', strandSpecializationId: 'strand-ict', adviserTeacherId: 'tch-necyl', roomId: 'rm-tle', status: 'Active' },
  { id: 'sec-12-acad', name: 'Grade 12 - Academic Strand', gradeLevelId: 'gl-12', schoolYearId: 'sy-2026-2027', trackProgramId: 'track-acad', strandSpecializationId: 'strand-humss', adviserTeacherId: 'tch-reven', roomId: 'rm-6', status: 'Active' },
  { id: 'sec-12-tech', name: 'Grade 12 - TechPro', gradeLevelId: 'gl-12', schoolYearId: 'sy-2026-2027', trackProgramId: 'track-techpro', strandSpecializationId: 'strand-ict', adviserTeacherId: 'tch-kimberly', roomId: 'rm-com', status: 'Active' },
];

export const initialSubjects: Subject[] = [
  // Grade 7 Subjects
  { id: 'sub-math7', subjectCode: 'MATH-7', subjectName: 'Mathematics 7', description: 'Numbers and Number Sense, Algebra, Geometry, Statistics and Probability', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-sci7', subjectCode: 'SCI-7', subjectName: 'Science 7', description: 'General Science, Living Things and Environment, Matter and Energy', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-eng7', subjectCode: 'ENG-7', subjectName: 'English 7', description: 'Philippine Literature, Grammar, Reading Comprehension, Oral Communication', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-fil7', subjectCode: 'FIL-7', subjectName: 'Filipino 7', description: 'Ibong Adarna, Panitikang Pilipino, Gramatika at Retorika', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-ap7', subjectCode: 'AP-7', subjectName: 'Araling Panlipunan 7', description: 'Araling Asyano (Asian Studies & Geography)', gradeLevelId: 'gl-7', units: 3, status: 'Active' },
  { id: 'sub-mapeh7', subjectCode: 'MAPEH-7', subjectName: 'MAPEH 7', description: 'Music, Arts, Physical Education, and Health 7', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-tle7', subjectCode: 'TLE-7', subjectName: 'TLE 7', description: 'Technology and Livelihood Education Exploratory Courses', gradeLevelId: 'gl-7', units: 4, status: 'Active' },
  { id: 'sub-esp7', subjectCode: 'ESP-7', subjectName: 'ESP 7', description: 'Edukasyon sa Pagpapakatao 7 - Mga Angkop na Inaasahang Kakayahan at Kilos', gradeLevelId: 'gl-7', units: 2, status: 'Active' },

  // Grade 8 Subjects
  { id: 'sub-math8', subjectCode: 'MATH-8', subjectName: 'Mathematics 8', description: 'Intermediate Algebra, Geometry, Probability', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-sci8', subjectCode: 'SCI-8', subjectName: 'Science 8', description: 'Force, Motion, Energy, Earth and Space, Digestive and Cellular Biology', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-eng8', subjectCode: 'ENG-8', subjectName: 'English 8', description: 'Afro-Asian Literature, Advanced Grammar, Creative Writing', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-fil8', subjectCode: 'FIL-8', subjectName: 'Filipino 8', description: 'Florante at Laura, Panitikang Pilipino', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-ap8', subjectCode: 'AP-8', subjectName: 'Araling Panlipunan 8', description: 'Kasaysayan ng Daigdig (World History)', gradeLevelId: 'gl-8', units: 3, status: 'Active' },
  { id: 'sub-mapeh8', subjectCode: 'MAPEH-8', subjectName: 'MAPEH 8', description: 'Music, Arts, Physical Education, and Health 8', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-tle8', subjectCode: 'TLE-8', subjectName: 'TLE 8', description: 'Technology and Livelihood Education Specializations', gradeLevelId: 'gl-8', units: 4, status: 'Active' },
  { id: 'sub-esp8', subjectCode: 'ESP-8', subjectName: 'ESP 8', description: 'Edukasyon sa Pagpapakatao 8 - Pakikipagkapwa at Pamilya', gradeLevelId: 'gl-8', units: 2, status: 'Active' },

  // Grade 9 & 10 Subjects
  { id: 'sub-math9', subjectCode: 'MATH-9', subjectName: 'Mathematics 9', description: 'Quadratic Equations, Trigonometry and Geometry', gradeLevelId: 'gl-9', units: 4, status: 'Active' },
  { id: 'sub-sci9', subjectCode: 'SCI-9', subjectName: 'Science 9', description: 'Genetics, Atomic Structure, Earth and Climate', gradeLevelId: 'gl-9', units: 4, status: 'Active' },
  { id: 'sub-math10', subjectCode: 'MATH-10', subjectName: 'Mathematics 10', description: 'Sequences and Series, Polynomials, Analytic Geometry', gradeLevelId: 'gl-10', units: 4, status: 'Active' },
  { id: 'sub-sci10', subjectCode: 'SCI-10', subjectName: 'Science 10', description: 'Plate Tectonics, Electromagnetic Spectrum, Heredity and Evolution', gradeLevelId: 'gl-10', units: 4, status: 'Active' },

  // Senior High School (Grade 11 & 12) Core & Specialized
  { id: 'sub-genmath11', subjectCode: 'SHS-GMATH', subjectName: 'General Mathematics', description: 'Functions, Business Mathematics, Logic', gradeLevelId: 'gl-11', trackProgramId: 'track-acad', units: 4, status: 'Active' },
  { id: 'sub-oralcomm11', subjectCode: 'SHS-OCOMM', subjectName: 'Oral Communication in Context', description: 'Principles and practice of effective communication', gradeLevelId: 'gl-11', units: 4, status: 'Active' },
  { id: 'sub-physci11', subjectCode: 'SHS-PSCI', subjectName: 'Physical Science', description: 'Evolution of our understanding of matter and the universe', gradeLevelId: 'gl-11', units: 4, status: 'Active' },
  { id: 'sub-emptech11', subjectCode: 'SHS-ETECH', subjectName: 'Empowerment Technologies', description: 'Information and Communication Technology for Professional Tracks', gradeLevelId: 'gl-11', trackProgramId: 'track-techpro', units: 4, status: 'Active' },
  { id: 'sub-techprog12', subjectCode: 'TECH-PRO1', subjectName: 'TechPro Specialization Practicum I', description: 'Hands-on practical industry competency training and assessment', gradeLevelId: 'gl-12', trackProgramId: 'track-techpro', units: 6, status: 'Active' },
];

export const initialTeacherAssignments: TeacherAssignment[] = [
  // Austin
  { id: 'ta-1', teacherId: 'tch-austin', subjectId: 'sub-math7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-2', teacherId: 'tch-austin', subjectId: 'sub-esp7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-3', teacherId: 'tch-austin', subjectId: 'sub-math7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },
  
  // Eunilyn
  { id: 'ta-4', teacherId: 'tch-eunilyn', subjectId: 'sub-sci7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-5', teacherId: 'tch-eunilyn', subjectId: 'sub-sci7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-6', teacherId: 'tch-eunilyn', subjectId: 'sub-sci8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },
  
  // Angela
  { id: 'ta-7', teacherId: 'tch-angela', subjectId: 'sub-tle7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-8', teacherId: 'tch-angela', subjectId: 'sub-tle7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-9', teacherId: 'tch-angela', subjectId: 'sub-tle8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },

  // Jenneth
  { id: 'ta-10', teacherId: 'tch-jenneth', subjectId: 'sub-eng7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-11', teacherId: 'tch-jenneth', subjectId: 'sub-eng7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-12', teacherId: 'tch-jenneth', subjectId: 'sub-eng8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },

  // Merilyn
  { id: 'ta-13', teacherId: 'tch-merilyn', subjectId: 'sub-math8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-14', teacherId: 'tch-merilyn', subjectId: 'sub-esp8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-15', teacherId: 'tch-merilyn', subjectId: 'sub-math9', sectionId: 'sec-9a', schoolYearId: 'sy-2026-2027' },

  // Jhopay
  { id: 'ta-16', teacherId: 'tch-jhopay', subjectId: 'sub-fil7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-17', teacherId: 'tch-jhopay', subjectId: 'sub-fil7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-18', teacherId: 'tch-jhopay', subjectId: 'sub-fil8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },

  // Judith
  { id: 'ta-19', teacherId: 'tch-judith', subjectId: 'sub-mapeh7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-20', teacherId: 'tch-judith', subjectId: 'sub-mapeh7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },

  // Lyncha
  { id: 'ta-21', teacherId: 'tch-lyncha', subjectId: 'sub-ap7', sectionId: 'sec-7a', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-22', teacherId: 'tch-lyncha', subjectId: 'sub-ap7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },

  // Teresita
  { id: 'ta-23', teacherId: 'tch-teresita', subjectId: 'sub-esp7', sectionId: 'sec-7b', schoolYearId: 'sy-2026-2027' },

  // Kimberly
  { id: 'ta-24', teacherId: 'tch-kimberly', subjectId: 'sub-tle8', sectionId: 'sec-8b', schoolYearId: 'sy-2026-2027' },

  // Necyl
  { id: 'ta-25', teacherId: 'tch-necyl', subjectId: 'sub-emptech11', sectionId: 'sec-11-tech', schoolYearId: 'sy-2026-2027' },

  // Diosdado
  { id: 'ta-26', teacherId: 'tch-diosdado', subjectId: 'sub-mapeh8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },

  // Leonor
  { id: 'ta-27', teacherId: 'tch-leonor', subjectId: 'sub-ap8', sectionId: 'sec-8a', schoolYearId: 'sy-2026-2027' },

  // Mergie
  { id: 'ta-28', teacherId: 'tch-mergie', subjectId: 'sub-math10', sectionId: 'sec-10a', schoolYearId: 'sy-2026-2027' },

  // Reven
  { id: 'ta-29', teacherId: 'tch-reven', subjectId: 'sub-oralcomm11', sectionId: 'sec-11-acad', schoolYearId: 'sy-2026-2027' },

  // Sheila Mae
  { id: 'ta-30', teacherId: 'tch-sheilamae', subjectId: 'sub-sci9', sectionId: 'sec-9a', schoolYearId: 'sy-2026-2027' },

  // Morano
  { id: 'ta-31', teacherId: 'tch-morano', subjectId: 'sub-physci11', sectionId: 'sec-11-acad', schoolYearId: 'sy-2026-2027' },
  { id: 'ta-32', teacherId: 'tch-morano', subjectId: 'sub-sci10', sectionId: 'sec-10a', schoolYearId: 'sy-2026-2027' },
];

export const initialSchedules: Schedule[] = [
  // Grade 7 St. Joseph (Room 1) - Monday Schedule
  { id: 'sch-1', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '07:45', endTime: '08:35', teacherId: 'tch-austin', subjectId: 'sub-math7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-2', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '08:35', endTime: '09:25', teacherId: 'tch-austin', subjectId: 'sub-esp7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-3', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '09:40', endTime: '10:30', teacherId: 'tch-eunilyn', subjectId: 'sub-sci7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-4', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '10:30', endTime: '11:20', teacherId: 'tch-angela', subjectId: 'sub-tle7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-5', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '13:00', endTime: '13:50', teacherId: 'tch-jenneth', subjectId: 'sub-eng7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-6', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '13:50', endTime: '14:40', teacherId: 'tch-jhopay', subjectId: 'sub-fil7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-7', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '14:40', endTime: '15:30', teacherId: 'tch-lyncha', subjectId: 'sub-ap7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },
  { id: 'sch-8', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '15:30', endTime: '16:20', teacherId: 'tch-judith', subjectId: 'sub-mapeh7', gradeLevelId: 'gl-7', sectionId: 'sec-7a', roomId: 'rm-1' },

  // Grade 7 St. Jude (Room 2) - Monday Schedule
  { id: 'sch-9', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '07:45', endTime: '08:35', teacherId: 'tch-jenneth', subjectId: 'sub-eng7', gradeLevelId: 'gl-7', sectionId: 'sec-7b', roomId: 'rm-2' },
  { id: 'sch-10', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '08:35', endTime: '09:25', teacherId: 'tch-eunilyn', subjectId: 'sub-sci7', gradeLevelId: 'gl-7', sectionId: 'sec-7b', roomId: 'rm-2' },
  { id: 'sch-11', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '09:40', endTime: '10:30', teacherId: 'tch-austin', subjectId: 'sub-math7', gradeLevelId: 'gl-7', sectionId: 'sec-7b', roomId: 'rm-2' },
  { id: 'sch-12', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '10:30', endTime: '11:20', teacherId: 'tch-teresita', subjectId: 'sub-esp7', gradeLevelId: 'gl-7', sectionId: 'sec-7b', roomId: 'rm-2' },

  // Grade 8 St. Francis (Room 3) - Monday Schedule
  { id: 'sch-13', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '07:45', endTime: '08:35', teacherId: 'tch-merilyn', subjectId: 'sub-math8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-14', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '08:35', endTime: '09:25', teacherId: 'tch-jhopay', subjectId: 'sub-fil8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-15', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '09:40', endTime: '10:30', teacherId: 'tch-jenneth', subjectId: 'sub-eng8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-16', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '10:30', endTime: '11:20', teacherId: 'tch-eunilyn', subjectId: 'sub-sci8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-17', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '13:00', endTime: '13:50', teacherId: 'tch-angela', subjectId: 'sub-tle8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-18', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '13:50', endTime: '14:40', teacherId: 'tch-leonor', subjectId: 'sub-ap8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-19', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '14:40', endTime: '15:30', teacherId: 'tch-diosdado', subjectId: 'sub-mapeh8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },
  { id: 'sch-20', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '15:30', endTime: '16:20', teacherId: 'tch-merilyn', subjectId: 'sub-esp8', gradeLevelId: 'gl-8', sectionId: 'sec-8a', roomId: 'rm-3' },

  // Senior High Grade 11 - Academic Strand (Room 5)
  { id: 'sch-21', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '08:00', endTime: '09:30', teacherId: 'tch-morano', subjectId: 'sub-physci11', gradeLevelId: 'gl-11', sectionId: 'sec-11-acad', roomId: 'rm-5', trackProgramId: 'track-acad', strandSpecializationId: 'strand-stem' },
  { id: 'sch-22', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '09:45', endTime: '11:15', teacherId: 'tch-reven', subjectId: 'sub-oralcomm11', gradeLevelId: 'gl-11', sectionId: 'sec-11-acad', roomId: 'rm-5', trackProgramId: 'track-acad', strandSpecializationId: 'strand-stem' },

  // Senior High Grade 11 - TechPro (TLE Workshop)
  { id: 'sch-23', schoolYearId: 'sy-2026-2027', dayOfWeek: 'Monday', startTime: '08:00', endTime: '10:00', teacherId: 'tch-necyl', subjectId: 'sub-emptech11', gradeLevelId: 'gl-11', sectionId: 'sec-11-tech', roomId: 'rm-tle', trackProgramId: 'track-techpro', strandSpecializationId: 'strand-ict' },
];

export const initialStudents: Student[] = [
  {
    id: 'stud-1',
    studentId: 'SHA-2026-0001',
    lrn: '112233445566',
    firstName: 'Joshua',
    middleName: 'Alcantara',
    lastName: 'Melante',
    fullName: 'Joshua A. Melante',
    birthdate: '2013-05-14',
    sex: 'Male',
    address: 'Brgy. San Jose, Garchitorena, Camarines Sur',
    contactNumber: '0912-345-6789',
    email: 'joshua.melante@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Maria Melante',
    guardianContact: '0917-888-9911',
    gradeLevelId: 'gl-7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'stud-2',
    studentId: 'SHA-2026-0002',
    lrn: '112233445567',
    firstName: 'Kaye',
    middleName: 'Bautista',
    lastName: 'Reyes',
    fullName: 'Kaye B. Reyes',
    birthdate: '2013-08-20',
    sex: 'Female',
    address: 'Brgy. Bahi, Garchitorena, Camarines Sur',
    contactNumber: '0912-456-7890',
    email: 'kaye.reyes@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Roberto Reyes',
    guardianContact: '0918-777-6622',
    gradeLevelId: 'gl-7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T08:15:00Z',
  },
  {
    id: 'stud-3',
    studentId: 'SHA-2026-0003',
    lrn: '112233445568',
    firstName: 'Christian',
    middleName: 'Dela Cruz',
    lastName: 'Santos',
    fullName: 'Christian D. Santos',
    birthdate: '2012-11-03',
    sex: 'Male',
    address: 'Poblacion, Garchitorena, Camarines Sur',
    contactNumber: '0912-567-8901',
    email: 'christian.santos@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Elena Santos',
    guardianContact: '0919-666-5533',
    gradeLevelId: 'gl-8',
    sectionId: 'sec-8a',
    schoolYearId: 'sy-2026-2027',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T08:30:00Z',
  },
  {
    id: 'stud-4',
    studentId: 'SHA-2026-0004',
    lrn: '112233445569',
    firstName: 'Angelica',
    middleName: 'Gomez',
    lastName: 'Villanueva',
    fullName: 'Angelica G. Villanueva',
    birthdate: '2011-04-18',
    sex: 'Female',
    address: 'Brgy. Canuto, Garchitorena, Camarines Sur',
    contactNumber: '0912-678-9012',
    email: 'angelica.villanueva@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Arthur Villanueva',
    guardianContact: '0920-555-4422',
    gradeLevelId: 'gl-9',
    sectionId: 'sec-9a',
    schoolYearId: 'sy-2026-2027',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T08:45:00Z',
  },
  {
    id: 'stud-5',
    studentId: 'SHA-2026-0005',
    lrn: '112233445570',
    firstName: 'Mark Anthony',
    middleName: 'Flores',
    lastName: 'Castillo',
    fullName: 'Mark Anthony F. Castillo',
    birthdate: '2010-09-27',
    sex: 'Male',
    address: 'Brgy. Del Pilar, Garchitorena, Camarines Sur',
    contactNumber: '0912-789-0123',
    email: 'mark.castillo@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Carmela Castillo',
    guardianContact: '0921-444-3311',
    gradeLevelId: 'gl-10',
    sectionId: 'sec-10a',
    schoolYearId: 'sy-2026-2027',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'stud-6',
    studentId: 'SHA-2026-0006',
    lrn: '112233445571',
    firstName: 'Patricia Mae',
    middleName: 'Rosales',
    lastName: 'Navarro',
    fullName: 'Patricia Mae R. Navarro',
    birthdate: '2009-02-14',
    sex: 'Female',
    address: 'Poblacion, Garchitorena, Camarines Sur',
    contactNumber: '0912-890-1234',
    email: 'patricia.navarro@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Felipe Navarro',
    guardianContact: '0922-333-2200',
    gradeLevelId: 'gl-11',
    sectionId: 'sec-11-acad',
    schoolYearId: 'sy-2026-2027',
    trackProgramId: 'track-acad',
    strandSpecializationId: 'strand-stem',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T09:15:00Z',
  },
  {
    id: 'stud-7',
    studentId: 'SHA-2026-0007',
    lrn: '112233445572',
    firstName: 'John Paul',
    middleName: 'Perez',
    lastName: 'Bautista',
    fullName: 'John Paul P. Bautista',
    birthdate: '2009-07-30',
    sex: 'Male',
    address: 'Brgy. Toytoy, Garchitorena, Camarines Sur',
    contactNumber: '0912-901-2345',
    email: 'johnpaul.bautista@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Luzviminda Bautista',
    guardianContact: '0923-222-1199',
    gradeLevelId: 'gl-11',
    sectionId: 'sec-11-tech',
    schoolYearId: 'sy-2026-2027',
    trackProgramId: 'track-techpro',
    strandSpecializationId: 'strand-ict',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T09:30:00Z',
  },
  {
    id: 'stud-8',
    studentId: 'SHA-2026-0008',
    lrn: '112233445573',
    firstName: 'Janelle',
    middleName: 'Cortez',
    lastName: 'Alvarez',
    fullName: 'Janelle C. Alvarez',
    birthdate: '2008-12-05',
    sex: 'Female',
    address: 'Brgy. Cagnipa, Garchitorena, Camarines Sur',
    contactNumber: '0913-012-3456',
    email: 'janelle.alvarez@student.sacredheartacademy.edu.ph',
    parentGuardian: 'Danilo Alvarez',
    guardianContact: '0924-111-0088',
    gradeLevelId: 'gl-12',
    sectionId: 'sec-12-acad',
    schoolYearId: 'sy-2026-2027',
    trackProgramId: 'track-acad',
    strandSpecializationId: 'strand-humss',
    enrollmentStatus: 'Active',
    createdAt: '2026-08-01T09:45:00Z',
  },
];

export const initialEnrollments: StudentEnrollment[] = initialStudents.map((s, idx) => ({
  id: `enr-${idx + 1}`,
  studentId: s.id,
  schoolYearId: s.schoolYearId,
  gradeLevelId: s.gradeLevelId,
  sectionId: s.sectionId,
  trackProgramId: s.trackProgramId,
  strandSpecializationId: s.strandSpecializationId,
  enrollmentStatus: s.enrollmentStatus,
  enrollmentDate: '2026-08-01',
}));

export const initialGrades: GradeRecord[] = [
  // Joshua Melante (Grade 7 St. Joseph)
  {
    id: 'grd-1',
    studentId: 'stud-1',
    subjectId: 'sub-math7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-austin',
    q1: 89,
    q2: 91,
    q3: null,
    q4: null,
    finalGrade: 90,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T10:00:00Z',
    approvedAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'grd-2',
    studentId: 'stud-1',
    subjectId: 'sub-esp7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-austin',
    q1: 92,
    q2: 94,
    q3: null,
    q4: null,
    finalGrade: 93,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T10:00:00Z',
    approvedAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'grd-3',
    studentId: 'stud-1',
    subjectId: 'sub-sci7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-eunilyn',
    q1: 88,
    q2: 90,
    q3: null,
    q4: null,
    finalGrade: 89,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T11:00:00Z',
    approvedAt: '2026-08-16T14:30:00Z',
  },
  {
    id: 'grd-4',
    studentId: 'stud-1',
    subjectId: 'sub-eng7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-jenneth',
    q1: 90,
    q2: 92,
    q3: null,
    q4: null,
    finalGrade: 91,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T11:30:00Z',
    approvedAt: '2026-08-16T14:45:00Z',
  },
  {
    id: 'grd-5',
    studentId: 'stud-1',
    subjectId: 'sub-fil7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-jhopay',
    q1: 91,
    q2: 89,
    q3: null,
    q4: null,
    finalGrade: 90,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T12:00:00Z',
    approvedAt: '2026-08-16T15:00:00Z',
  },
  {
    id: 'grd-6',
    studentId: 'stud-1',
    subjectId: 'sub-ap7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-lyncha',
    q1: 87,
    q2: 88,
    q3: null,
    q4: null,
    finalGrade: 88,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T12:30:00Z',
    approvedAt: '2026-08-16T15:15:00Z',
  },
  {
    id: 'grd-7',
    studentId: 'stud-1',
    subjectId: 'sub-mapeh7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-judith',
    q1: 93,
    q2: 95,
    q3: null,
    q4: null,
    finalGrade: 94,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T13:00:00Z',
    approvedAt: '2026-08-16T15:30:00Z',
  },
  {
    id: 'grd-8',
    studentId: 'stud-1',
    subjectId: 'sub-tle7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-angela',
    q1: 91,
    q2: 93,
    q3: null,
    q4: null,
    finalGrade: 92,
    remarks: 'Passed',
    status: 'Published',
    submittedAt: '2026-08-15T13:30:00Z',
    approvedAt: '2026-08-16T15:45:00Z',
  },

  // Kaye Reyes (Grade 7 St. Joseph)
  {
    id: 'grd-9',
    studentId: 'stud-2',
    subjectId: 'sub-math7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-austin',
    q1: 94,
    q2: 95,
    q3: null,
    q4: null,
    finalGrade: 95,
    remarks: 'Passed with Honors',
    status: 'Published',
    submittedAt: '2026-08-15T10:00:00Z',
    approvedAt: '2026-08-16T14:00:00Z',
  },
  {
    id: 'grd-10',
    studentId: 'stud-2',
    subjectId: 'sub-sci7',
    sectionId: 'sec-7a',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-eunilyn',
    q1: 92,
    q2: 93,
    q3: null,
    q4: null,
    finalGrade: 93,
    remarks: 'Passed',
    status: 'Approved',
    submittedAt: '2026-08-15T11:00:00Z',
    approvedAt: '2026-08-16T14:30:00Z',
  },

  // Patricia Mae Navarro (Grade 11 STEM)
  {
    id: 'grd-11',
    studentId: 'stud-6',
    subjectId: 'sub-physci11',
    sectionId: 'sec-11-acad',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-morano',
    q1: 93,
    q2: 94,
    q3: null,
    q4: null,
    finalGrade: 94,
    remarks: 'Passed',
    status: 'Submitted',
    submittedAt: '2026-08-20T09:00:00Z',
  },
  {
    id: 'grd-12',
    studentId: 'stud-6',
    subjectId: 'sub-oralcomm11',
    sectionId: 'sec-11-acad',
    schoolYearId: 'sy-2026-2027',
    teacherId: 'tch-reven',
    q1: 90,
    q2: null,
    q3: null,
    q4: null,
    finalGrade: null,
    remarks: 'In Progress',
    status: 'Draft',
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Welcome to School Year 2026–2027: Commitment to Academic Excellence & Faith',
    content: 'Welcome back, beloved faculty, students, and stakeholders of Sacred Heart Academy! As we commence School Year 2026–2027, let us embody the values of integrity, scholarship, and community service in all our academic and co-curricular endeavors.',
    authorName: 'Atty. Rammonete Shirlyn G. Piano',
    authorRole: 'HEAD',
    targetAudience: 'School-Wide',
    publishDate: '2026-08-01',
    isPinned: true,
    priority: 'High',
  },
  {
    id: 'ann-2',
    title: 'First Quarter Examination Schedule & Grade Encoding Guidelines',
    content: 'All faculty members are reminded that the 1st Quarter Examinations will be held on the last week of October 2026. Grade draft encoding across all subjects must be completed within 5 working days following the examination period.',
    authorName: 'Ellen Baider',
    authorRole: 'PRINCIPAL',
    targetAudience: 'Teachers-Only',
    publishDate: '2026-08-10',
    isPinned: true,
    priority: 'Normal',
  },
  {
    id: 'ann-3',
    title: 'Registrar Advisory: Submission of Form 137 / SF10 Requirements for Transferees & JHS Enrollees',
    content: 'All newly enrolled Grade 7 learners and Senior High School transferees are requested to submit their official Form 137 (Learner Permanent Academic Record) or PSA Birth Certificate copy to the Office of the Registrar.',
    authorName: 'Ruben Martirez',
    authorRole: 'REGISTRAR',
    targetAudience: 'School-Wide',
    publishDate: '2026-08-12',
    isPinned: false,
    priority: 'Normal',
  },
  {
    id: 'ann-4',
    title: 'Senior High School Track Orientation: Academic Strand & TechPro Specializations',
    content: 'Grade 10 Completers and Grade 11 entrants are invited to attend the SHS Track & TechPro Career Pathways Orientation this Friday at the Audio-Visual Room (AVR).',
    authorName: 'Ellen Baider',
    authorRole: 'PRINCIPAL',
    targetAudience: 'SHS-Only',
    gradeLevelId: 'gl-11',
    publishDate: '2026-08-18',
    isPinned: false,
    priority: 'Normal',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-admin',
    userName: 'System Administrator',
    userRole: 'ADMIN',
    action: 'SYSTEM_INITIALIZATION',
    module: 'System',
    description: 'Initial school system database established with Sacred Heart Academy master catalog, officials, and timetable.',
    timestamp: '2026-08-01T08:00:00Z',
    ipAddress: '192.168.1.1',
  },
  {
    id: 'log-2',
    userId: 'user-head',
    userName: 'Atty. Rammonete Shirlyn G. Piano',
    userRole: 'HEAD',
    action: 'POST_ANNOUNCEMENT',
    module: 'Announcements',
    recordId: 'ann-1',
    description: 'Published School-Wide welcome message for SY 2026–2027.',
    timestamp: '2026-08-01T09:00:00Z',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'log-3',
    userId: 'user-registrar',
    userName: 'Ruben Martirez',
    userRole: 'REGISTRAR',
    action: 'ENROLL_STUDENT',
    module: 'Enrollment',
    recordId: 'stud-1',
    description: 'Enrolled student Joshua Melante in Grade 7 Section St. Joseph.',
    timestamp: '2026-08-01T09:30:00Z',
    ipAddress: '192.168.1.15',
  },
  {
    id: 'log-4',
    userId: 'user-teacher-austin',
    userName: 'Austin Mercado',
    userRole: 'TEACHER',
    action: 'SUBMIT_GRADES',
    module: 'Grading',
    recordId: 'grd-1',
    description: 'Teacher Austin submitted Grade 7 Mathematics 1st & 2nd Quarter grades for Section St. Joseph.',
    timestamp: '2026-08-15T10:00:00Z',
    ipAddress: '192.168.1.102',
  },
  {
    id: 'log-5',
    userId: 'user-principal',
    userName: 'Ellen Baider',
    userRole: 'PRINCIPAL',
    action: 'APPROVE_GRADES',
    module: 'Grading',
    recordId: 'grd-1',
    description: 'Principal Ellen Baider approved Grade 7 Mathematics grades submitted by Teacher Austin.',
    timestamp: '2026-08-16T14:00:00Z',
    ipAddress: '192.168.1.20',
  },
];

export const initialUsers: User[] = [
  {
    id: 'user-admin',
    username: 'admin',
    email: 'admin@sacredheartacademy-garchitorena.edu.ph',
    fullName: 'System Administrator',
    role: 'ADMIN',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-head',
    username: 'head',
    email: 'head@sacredheartacademy-garchitorena.edu.ph',
    fullName: 'Atty. Rammonete Shirlyn G. Piano',
    role: 'HEAD',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-principal',
    username: 'principal',
    email: 'principal@sacredheartacademy-garchitorena.edu.ph',
    fullName: 'Ellen Baider',
    role: 'PRINCIPAL',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-registrar',
    username: 'registrar',
    email: 'registrar@sacredheartacademy-garchitorena.edu.ph',
    fullName: 'Ruben Martirez',
    role: 'REGISTRAR',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  // Initial Teachers as Users
  {
    id: 'user-teacher-austin',
    username: 'austin',
    email: 'austin@sacredheartacademy.edu.ph',
    fullName: 'Teacher Austin',
    role: 'TEACHER',
    relatedEntityId: 'tch-austin',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-eunilyn',
    username: 'eunilyn',
    email: 'eunilyn@sacredheartacademy.edu.ph',
    fullName: 'Teacher Eunilyn',
    role: 'TEACHER',
    relatedEntityId: 'tch-eunilyn',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-angela',
    username: 'angela',
    email: 'angela@sacredheartacademy.edu.ph',
    fullName: 'Teacher Angela',
    role: 'TEACHER',
    relatedEntityId: 'tch-angela',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-jenneth',
    username: 'jenneth',
    email: 'jenneth@sacredheartacademy.edu.ph',
    fullName: 'Teacher Jenneth',
    role: 'TEACHER',
    relatedEntityId: 'tch-jenneth',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-merilyn',
    username: 'merilyn',
    email: 'merilyn@sacredheartacademy.edu.ph',
    fullName: 'Teacher Merilyn',
    role: 'TEACHER',
    relatedEntityId: 'tch-merilyn',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-jhopay',
    username: 'jhopay',
    email: 'jhopay@sacredheartacademy.edu.ph',
    fullName: 'Teacher Jhopay',
    role: 'TEACHER',
    relatedEntityId: 'tch-jhopay',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-judith',
    username: 'judith',
    email: 'judith@sacredheartacademy.edu.ph',
    fullName: 'Teacher Judith',
    role: 'TEACHER',
    relatedEntityId: 'tch-judith',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-lyncha',
    username: 'lyncha',
    email: 'lyncha@sacredheartacademy.edu.ph',
    fullName: 'Teacher Lyncha',
    role: 'TEACHER',
    relatedEntityId: 'tch-lyncha',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-teresita',
    username: 'teresita',
    email: 'teresita@sacredheartacademy.edu.ph',
    fullName: 'Teacher Teresita',
    role: 'TEACHER',
    relatedEntityId: 'tch-teresita',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-kimberly',
    username: 'kimberly',
    email: 'kimberly@sacredheartacademy.edu.ph',
    fullName: 'Teacher Kimberly',
    role: 'TEACHER',
    relatedEntityId: 'tch-kimberly',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-necyl',
    username: 'necyl',
    email: 'necyl@sacredheartacademy.edu.ph',
    fullName: 'Teacher Necyl',
    role: 'TEACHER',
    relatedEntityId: 'tch-necyl',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-diosdado',
    username: 'diosdado',
    email: 'diosdado@sacredheartacademy.edu.ph',
    fullName: 'Teacher Diosdado',
    role: 'TEACHER',
    relatedEntityId: 'tch-diosdado',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-leonor',
    username: 'leonor',
    email: 'leonor@sacredheartacademy.edu.ph',
    fullName: 'Teacher Leonor',
    role: 'TEACHER',
    relatedEntityId: 'tch-leonor',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-mergie',
    username: 'mergie',
    email: 'mergie@sacredheartacademy.edu.ph',
    fullName: 'Teacher Mergie',
    role: 'TEACHER',
    relatedEntityId: 'tch-mergie',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-reven',
    username: 'reven',
    email: 'reven@sacredheartacademy.edu.ph',
    fullName: 'Teacher Reven',
    role: 'TEACHER',
    relatedEntityId: 'tch-reven',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-sheilamae',
    username: 'sheilamae',
    email: 'sheilamae@sacredheartacademy.edu.ph',
    fullName: 'Teacher Sheila Mae',
    role: 'TEACHER',
    relatedEntityId: 'tch-sheilamae',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  {
    id: 'user-teacher-morano',
    username: 'morano',
    email: 'morano@sacredheartacademy.edu.ph',
    fullName: 'Teacher Morano',
    role: 'TEACHER',
    relatedEntityId: 'tch-morano',
    status: 'Active',
    createdAt: '2026-08-01',
  },
  // Student User
  {
    id: 'user-stud-joshua',
    username: 'joshua',
    email: 'joshua.melante@student.sacredheartacademy.edu.ph',
    fullName: 'Joshua A. Melante',
    role: 'STUDENT',
    relatedEntityId: 'stud-1',
    status: 'Active',
    createdAt: '2026-08-01',
  },
];

export const initialRolePermissions: RolePermissionConfig[] = [
  {
    role: 'ADMIN',
    displayName: 'System Administrator',
    description: 'Comprehensive system control and institutional configuration',
    canManageStudents: true,
    canManageTeachers: true,
    canManageSubjects: true,
    canManageSections: true,
    canManageSchedules: true,
    canEncodeGrades: true,
    canApproveGrades: true,
    canPublishGrades: true,
    canPostAnnouncements: true,
    canGenerateReports: true,
    canManageSettings: true,
    canViewAuditLogs: true,
  },
  {
    role: 'HEAD',
    displayName: 'School Head',
    assignedOfficial: 'Atty. Rammonete Shirlyn G. Piano',
    description: 'Executive institutional oversight, policy supervision, and high-level academic review',
    canManageStudents: false,
    canManageTeachers: false,
    canManageSubjects: false,
    canManageSections: false,
    canManageSchedules: false,
    canEncodeGrades: false,
    canApproveGrades: true,
    canPublishGrades: true,
    canPostAnnouncements: true,
    canGenerateReports: true,
    canManageSettings: false,
    canViewAuditLogs: true,
  },
  {
    role: 'PRINCIPAL',
    displayName: 'School Principal',
    assignedOfficial: 'Ellen Baider',
    description: 'Academic administration, curriculum supervision, teacher monitoring, and grade review/approval',
    canManageStudents: false,
    canManageTeachers: false,
    canManageSubjects: false,
    canManageSections: false,
    canManageSchedules: true,
    canEncodeGrades: false,
    canApproveGrades: true,
    canPublishGrades: true,
    canPostAnnouncements: true,
    canGenerateReports: true,
    canManageSettings: false,
    canViewAuditLogs: true,
  },
  {
    role: 'REGISTRAR',
    displayName: 'School Registrar',
    assignedOfficial: 'Ruben Martirez',
    description: 'Student registration, enrollment processing, official academic records, and transcript masterlists',
    canManageStudents: true,
    canManageTeachers: false,
    canManageSubjects: false,
    canManageSections: true,
    canManageSchedules: false,
    canEncodeGrades: false,
    canApproveGrades: false,
    canPublishGrades: false,
    canPostAnnouncements: true,
    canGenerateReports: true,
    canManageSettings: false,
    canViewAuditLogs: false,
  },
  {
    role: 'TEACHER',
    displayName: 'Classroom Teacher',
    description: 'Subject instruction, classroom advisory, student progress monitoring, and grade encoding',
    canManageStudents: false,
    canManageTeachers: false,
    canManageSubjects: false,
    canManageSections: false,
    canManageSchedules: false,
    canEncodeGrades: true,
    canApproveGrades: false,
    canPublishGrades: false,
    canPostAnnouncements: true,
    canGenerateReports: true,
    canManageSettings: false,
    canViewAuditLogs: false,
  },
  {
    role: 'STUDENT',
    displayName: 'Enrolled Student',
    description: 'Personal academic performance viewing, schedule checking, and school announcements',
    canManageStudents: false,
    canManageTeachers: false,
    canManageSubjects: false,
    canManageSections: false,
    canManageSchedules: false,
    canEncodeGrades: false,
    canApproveGrades: false,
    canPublishGrades: false,
    canPostAnnouncements: false,
    canGenerateReports: true,
    canManageSettings: false,
    canViewAuditLogs: false,
  },
];
